#ifndef GPIO_H_
#define GPIO_H_

#define GPIO_PORT_START_BUTTON		GPIO_PORT_P4
#define GPIO_PIN_START_BUTTON		GPIO_PIN5

#define GPIO_PORT_LED_GREEN			GPIO_PORT_P1
#define GPIO_PIN_LED_GREEN			GPIO_PIN0
#define GPIO_PORT_LED_RED			GPIO_PORT_P4
#define GPIO_PIN_LED_RED			GPIO_PIN6

#define GPIO_PORT_CAPUTRE_INDICATOR	GPIO_PORT_P1
#define GPIO_PIN_CAPUTRE_INDICATOR	GPIO_PIN6


void GPIO_init(void);
void GPIO_reset(void);

#endif /* GPIO_H_ */
